services:
  app:
    build: .
    command: python src/app.py
    depends_on:
      - postgres

  postgres:
    image: postgres:18.3
    environment:
      POSTGRES_USER: dbos
      POSTGRES_PASSWORD: password
